"""upload semana fecha

Revision ID: 5e4d8afdeb10
Revises: ff2da92fff2d
Create Date: 2026-07-20 19:39:21.577893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e4d8afdeb10'
down_revision: Union[str, None] = 'ff2da92fff2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploads', sa.Column('semana', sa.String(), nullable=False, server_default=''))
    op.alter_column('uploads', 'semana', server_default=None)
    op.add_column('uploads', sa.Column('fecha', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uploads', 'fecha')
    op.drop_column('uploads', 'semana')
    # ### end Alembic commands ###
