"""init schema

Revision ID: ff2da92fff2d
Revises: 
Create Date: 2026-07-20 17:47:07.657705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff2da92fff2d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('rol', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('uploads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('periodo', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('bucket_key', sa.String(), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uploads_periodo'), 'uploads', ['periodo'], unique=False)
    op.create_table('avance_semanal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('upload_id', sa.Integer(), nullable=False),
    sa.Column('periodo', sa.String(), nullable=False),
    sa.Column('semana', sa.String(), nullable=False),
    sa.Column('por_firmar', sa.Integer(), nullable=False),
    sa.Column('firmadas', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_avance_semanal_periodo'), 'avance_semanal', ['periodo'], unique=False)
    op.create_index(op.f('ix_avance_semanal_upload_id'), 'avance_semanal', ['upload_id'], unique=False)
    op.create_table('canal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('upload_id', sa.Integer(), nullable=False),
    sa.Column('periodo', sa.String(), nullable=False),
    sa.Column('canal', sa.String(), nullable=False),
    sa.Column('reservas', sa.Integer(), nullable=False),
    sa.Column('promesas', sa.Integer(), nullable=False),
    sa.Column('escrituras', sa.Integer(), nullable=False),
    sa.Column('desistidos', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_canal_periodo'), 'canal', ['periodo'], unique=False)
    op.create_index(op.f('ix_canal_upload_id'), 'canal', ['upload_id'], unique=False)
    op.create_table('evolucion_mensual',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('upload_id', sa.Integer(), nullable=False),
    sa.Column('periodo', sa.String(), nullable=False),
    sa.Column('mes', sa.String(), nullable=False),
    sa.Column('ofertas', sa.Integer(), nullable=False),
    sa.Column('promesas', sa.Integer(), nullable=False),
    sa.Column('escrituras', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evolucion_mensual_periodo'), 'evolucion_mensual', ['periodo'], unique=False)
    op.create_index(op.f('ix_evolucion_mensual_upload_id'), 'evolucion_mensual', ['upload_id'], unique=False)
    op.create_table('funnel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('upload_id', sa.Integer(), nullable=False),
    sa.Column('periodo', sa.String(), nullable=False),
    sa.Column('ofertas', sa.Integer(), nullable=False),
    sa.Column('desistidos', sa.Integer(), nullable=False),
    sa.Column('en_curso', sa.Integer(), nullable=False),
    sa.Column('promesas', sa.Integer(), nullable=False),
    sa.Column('escrituras', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_funnel_periodo'), 'funnel', ['periodo'], unique=False)
    op.create_index(op.f('ix_funnel_upload_id'), 'funnel', ['upload_id'], unique=False)
    op.create_table('grilla_unidades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('upload_id', sa.Integer(), nullable=False),
    sa.Column('periodo', sa.String(), nullable=False),
    sa.Column('torre', sa.Integer(), nullable=False),
    sa.Column('cara', sa.String(), nullable=False),
    sa.Column('piso', sa.Integer(), nullable=False),
    sa.Column('depto', sa.String(), nullable=False),
    sa.Column('estado', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grilla_unidades_periodo'), 'grilla_unidades', ['periodo'], unique=False)
    op.create_index(op.f('ix_grilla_unidades_upload_id'), 'grilla_unidades', ['upload_id'], unique=False)
    op.create_table('marketing_banco',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('upload_id', sa.Integer(), nullable=False),
    sa.Column('periodo', sa.String(), nullable=False),
    sa.Column('banco', sa.String(), nullable=False),
    sa.Column('pct', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketing_banco_periodo'), 'marketing_banco', ['periodo'], unique=False)
    op.create_index(op.f('ix_marketing_banco_upload_id'), 'marketing_banco', ['upload_id'], unique=False)
    op.create_table('marketing_kpis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('upload_id', sa.Integer(), nullable=False),
    sa.Column('periodo', sa.String(), nullable=False),
    sa.Column('visitas_sala', sa.Integer(), nullable=False),
    sa.Column('leads_efectivos', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketing_kpis_periodo'), 'marketing_kpis', ['periodo'], unique=False)
    op.create_index(op.f('ix_marketing_kpis_upload_id'), 'marketing_kpis', ['upload_id'], unique=False)
    op.create_table('marketing_medios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('upload_id', sa.Integer(), nullable=False),
    sa.Column('periodo', sa.String(), nullable=False),
    sa.Column('medio', sa.String(), nullable=False),
    sa.Column('cant', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketing_medios_periodo'), 'marketing_medios', ['periodo'], unique=False)
    op.create_index(op.f('ix_marketing_medios_upload_id'), 'marketing_medios', ['upload_id'], unique=False)
    op.create_table('stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('upload_id', sa.Integer(), nullable=False),
    sa.Column('periodo', sa.String(), nullable=False),
    sa.Column('torre', sa.Integer(), nullable=False),
    sa.Column('tipologia', sa.String(), nullable=False),
    sa.Column('disponible', sa.Integer(), nullable=False),
    sa.Column('reservado', sa.Integer(), nullable=False),
    sa.Column('promesado', sa.Integer(), nullable=False),
    sa.Column('escriturado', sa.Integer(), nullable=False),
    sa.Column('bloqueado', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_periodo'), 'stock', ['periodo'], unique=False)
    op.create_index(op.f('ix_stock_upload_id'), 'stock', ['upload_id'], unique=False)
    op.create_table('ventas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('upload_id', sa.Integer(), nullable=False),
    sa.Column('periodo', sa.String(), nullable=False),
    sa.Column('torre', sa.Integer(), nullable=False),
    sa.Column('venta_uf', sa.Float(), nullable=False),
    sa.Column('x_recibir_uf', sa.Float(), nullable=False),
    sa.Column('pagado_uf', sa.Float(), nullable=False),
    sa.Column('escriturados', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ventas_periodo'), 'ventas', ['periodo'], unique=False)
    op.create_index(op.f('ix_ventas_upload_id'), 'ventas', ['upload_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ventas_upload_id'), table_name='ventas')
    op.drop_index(op.f('ix_ventas_periodo'), table_name='ventas')
    op.drop_table('ventas')
    op.drop_index(op.f('ix_stock_upload_id'), table_name='stock')
    op.drop_index(op.f('ix_stock_periodo'), table_name='stock')
    op.drop_table('stock')
    op.drop_index(op.f('ix_marketing_medios_upload_id'), table_name='marketing_medios')
    op.drop_index(op.f('ix_marketing_medios_periodo'), table_name='marketing_medios')
    op.drop_table('marketing_medios')
    op.drop_index(op.f('ix_marketing_kpis_upload_id'), table_name='marketing_kpis')
    op.drop_index(op.f('ix_marketing_kpis_periodo'), table_name='marketing_kpis')
    op.drop_table('marketing_kpis')
    op.drop_index(op.f('ix_marketing_banco_upload_id'), table_name='marketing_banco')
    op.drop_index(op.f('ix_marketing_banco_periodo'), table_name='marketing_banco')
    op.drop_table('marketing_banco')
    op.drop_index(op.f('ix_grilla_unidades_upload_id'), table_name='grilla_unidades')
    op.drop_index(op.f('ix_grilla_unidades_periodo'), table_name='grilla_unidades')
    op.drop_table('grilla_unidades')
    op.drop_index(op.f('ix_funnel_upload_id'), table_name='funnel')
    op.drop_index(op.f('ix_funnel_periodo'), table_name='funnel')
    op.drop_table('funnel')
    op.drop_index(op.f('ix_evolucion_mensual_upload_id'), table_name='evolucion_mensual')
    op.drop_index(op.f('ix_evolucion_mensual_periodo'), table_name='evolucion_mensual')
    op.drop_table('evolucion_mensual')
    op.drop_index(op.f('ix_canal_upload_id'), table_name='canal')
    op.drop_index(op.f('ix_canal_periodo'), table_name='canal')
    op.drop_table('canal')
    op.drop_index(op.f('ix_avance_semanal_upload_id'), table_name='avance_semanal')
    op.drop_index(op.f('ix_avance_semanal_periodo'), table_name='avance_semanal')
    op.drop_table('avance_semanal')
    op.drop_index(op.f('ix_uploads_periodo'), table_name='uploads')
    op.drop_table('uploads')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
